### ISSUE TITLE
swift-bridge

### ISSUE THREAD

**Issue by chinedufn** [audulus/rui-ios#1]
Hey!

I stumbled upon this note:

https://github.com/audulus/rui-ios/blob/e9db2cfff33f8e3baf4d2298e1fccd765a3d5280/src/lib.rs#L5

What's missing for `swift-bridge` to meet your needs?

**Comment by wtholliday** [comment]
Hi! Thanks for getting in touch!

I just made a quick assessment based on the readme ("Phase 1, make it possible") and trying it out a little. Let me give it another shot :)

**Comment by chinedufn** [comment]
Ah got it! I'll probably ditch that section since it's a bit outdated (most signatures that you'd use in a real application are supported by now. I'm using the library in production.)

Cool cool thanks. 
Yeah I mainly opened the issue to see if you had any immediate needs since I'd be more than happy to make sure that your use case is supported.

If you end up playing with it feel very free to open an issue if you need anything.

Cheers!!

**Comment by wtholliday** [comment]
Hey @chinedufn ! All converted to swift-bridge now. Thanks for your help and great work!

**Comment by chinedufn** [comment]
Woo glad it's working! 
Please feel free to open issues if you run into anything that you'd like to see improved.

Cheers!
